### ISSUE TITLE
Create a local.yml docker-compose config

### ISSUE THREAD

**Issue by senderle** [joelslee/textbook#4]
This is self-explanatory but may not be trivial. We need to be able to run testing versions of the server locally. In theory this can be based on `local.yml` but will require some substantial tweaking, especially since we're relying on traefik to do domain-based routing right now. I have zero idea how to modify it to behave correctly when we don't *have* domain names defined.

It's likely that we'll have to do something like run voyant on a different port. If we can do that and can serve the zip files via django's local static server, then we might not need traefik, in which case we can use the simple node-based server that `local.yml` uses.

**Comment by joelsjlee** [comment]
So this is pretty much finished and merged into the master branch. That being said, a few notes:
1. I was able to use Node and Browsersync to have multiple proxies and ports. I was also able to host the static files with the voyant proxy. This is all in `gulpfile.js`.
2. Currently, django is running on `:3000` and voyant is running on `:4000`. To access a voyant analysis on articles, the urls should look like this `192.168.99.100:4000/?input=http://192.168.99.100:4000/corpora/Socialist.zip`
3. The .envs generator that Vince was working on needs to be configured with local urls as well. Currently, the links on the jekyll text will go to a `pennds.org` link because of line 56 in `voyant_gen/voyant_gen.py`.
