### ISSUE TITLE
django ValueError with open-graph-logo.png in assets folder 

### ISSUE THREAD

**Issue by joelsjlee** [joelslee/textbook#8]
We were running into problems with getting permissions for the /static_pages/assets folder so our work around was to have it already created in our clean slate version. However, when I run the server and put in a text, it takes in the text and gives a link, but then gives a 500 error when I click on the link. The server outputs this error below:

![django-error](https://user-images.githubusercontent.com/34225086/60533960-c8f1da00-9cce-11e9-98de-e50b5fbfae3d.JPG)

More specifically, 

`ValueError: Missing staticfiles manifest entry for 'open-graph-logo.png'`

Exiting the server, then doing `sudo docker-compose down` and `sudo docker-compose up` seems to fix everything however, and I can access the jekyll text. That is, its only throwing an error on the first time it runs. This might have something to do with us creating the assets folder beforehand.

**Comment by senderle** [comment]
This is a funky one. Every time Django starts up in the current config, it runs a management command called `collectstatic`. (You can see this in the `start` script in `compose/production/django/bin` or something like that.) 

The `collectstatic` command creates a manifest of all the static files and appends hashes to their names -- I guess to make sure that if they change, the old versions aren't served instead of the new ones. And maybe for other reasons. 

Anyway, if a new static file is added after `collectstatic` has run, we get this error, because there's no manifest entry for it. So the solution of this problem is to run `collectstatic` again. Going `down` and then `up` again causes that to happen. But so should `sudo docker-compose restart`, which is faster. (Also, test this to make sure this is actually the problem; if `restart` doesn't fix it, then this might not be the problem after all.)

But this obviously isn't a good long-term solution. 

In theory, it would work to re-run `collectstatic` automatically whenever the contents of `static_page/assets` change. But this still might leave a brief window when this error could still occur. And if I recall correctly, this error isn't one the server recovers from! The whole thing grinds to a halt and has to be restarted by hand. 

Yuck.

So my thinking now is that we need to do something else that I've heard about but never tried. 

The thing that does manifest creation is a `ManifestStaticFilesStorage` object. You can tell this object to be non-strict when it comes to this test. Static files missing from the manifest are tolerated. You do this by [setting the `manifest_strict` attribute of the `ManifestStaticFilesStorage` class to `False`](https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage.manifest_strict). But you are literally modifying the class itself, which means you actually have to create a subclass. 

This is pretty wonky and complicated but it is possible to do. Here's a stackoverflow answer that describes something similar.

https://stackoverflow.com/a/51580328/577088

That answer is very specific and I think will need to be tweaked to work for us. But the idea is there.

**Comment by joelsjlee** [comment]
So two things:

1. `sudo docker-compose restart` does also fix the problem.
2. The error actually doesn't grind everything to a halt, you can keep on getting the error and still do other things like access voyant, sign in/sign out. Would our potential solution still be the best option if this is the case? Or something like having a while-loop checking for changes in `static_page/assets`?

**Comment by senderle** [comment]
Ok, if it doesn't grind to a halt, then yeah, let's not implement the complicated subclassing solution, and just find a way to run collectstatic when static_page/assets changes.

I am not 100% certain what the right approach is. But it appears you can call management commands programmatically: 

https://stackoverflow.com/a/29914150/577088

So it might be possible to write it directly into the app somehow.

I find myself wondering whether we can catch the `ValueError` and run collectstatic in an except clause... that way there's no busy-waiting.

Looking at the traceback, I think you might be able to do this inside the view function that renders static pages. We're already doing some wonky stuff in there so this can't be worse than what we already have! It would be something like the Python version of "try to return the rendered template... if you get a ValueError and it is obviously about the static manifest, which we can tell by looking at the error string (a bad thing to do but we're going to do it anyway), then run collectstatic and then try to return the template again."

**Comment by joelsjlee** [comment]
I have seemed to have fixed the bug by using a try except block in the views function, but I'll do some more testing. Here's the code that was changed:

under `proxy/views.py`
I turned:
```return HttpsResponse(template.render(context))```
into:
```
try:
    return HttpResponse(template.render(context))
except ValueError:
    call_command('collectstatic', verbosity=0, interactive=False)
    return HttpResponse(template.render(context))
```
Also at the top, I added
```from django.core.management import call_commmand```
